version: "3"
volumes:
  db-data:
    external: true
  letsencrypt-html:
    external: false
  letsencrypt-data:
    external: false
services:
  api:
    build:
      context: ./api
    entrypoint: /app/bin/start
    env_file:
      - ./api/.env.production
    environment:
      - REDIS_URL=redis://redis:6379/
      - SIDEKIQ_REDIS_URL=redis://redis:6379/
      - ANYCABLE_REDIS_URL=redis://redis:6379/
      - CABLE_URL=ws://anycable:7008/cable
      - DATABASE_URL=postgres://postgres:@db/ourcodestyle_production
    depends_on:
      - redis
      - db
      - anycable
  sidekiq:
    build:
      context: ./api
    command: sidekiq
    env_file:
      - ./api/.env.production
    environment:
      - REDIS_URL=redis://redis:6379/
      - SIDEKIQ_REDIS_URL=redis://redis:6379/
      - ANYCABLE_REDIS_URL=redis://redis:6379/
      - CABLE_URL=ws://anycable:7008/cable
    depends_on:
      - redis
      - db
      - anycable
  webserver:
    build:
      context: ./webserver
    volumes:
      - letsencrypt-html:/letsencrypt-html
      - letsencrypt-data:/letsencrypt-data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - anycable
      - api
      - ui
  ui:
    image: 'fuksito/ourcodestyle_ui:2020.12.29.0'
  rpc:
    build:
      context: ./api
    command: anycable
    env_file:
      - ./api/.env.production
    environment:
      - REDIS_URL=redis://redis:6379/
      - SIDEKIQ_REDIS_URL=redis://redis:6379/
      - ANYCABLE_REDIS_URL=redis://redis:6379/
      - ANYCABLE_RPC_HOST=0.0.0.0:50051
    depends_on:
      - redis
      - db
  redis:
    image: 'redis:6.0.8-alpine'
  anycable:
    image: 'anycable/anycable-go:v0.6.1'
    ports:
      - "7008:7008"
    environment:
      - PORT=7008
      - REDIS_URL=redis://redis:6379/0
      - ANYCABLE_RPC_HOST=rpc:50051
    depends_on:
      - redis
      - rpc
  db:
    image: 'postgres:11.1-alpine'
    volumes:
      - db-data:/var/lib/postgresql/data
