version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./api:/app
    ports:
      - "4000:3000"
    env_file:
      - ./api/.env.development
    environment:
      - ANYCABLE_REDIS_URL=redis://redis:6379/
      - CABLE_URL=ws://localhost:8080/cable
    depends_on:
      - redis
      - db
  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile.localhost
    ports:
      - "80:80"
    depends_on:
      - anycable
      - api
  rpc:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./bin/anycable
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.development
    environment:
      - ANYCABLE_REDIS_URL=redis://redis:6379/
      - ANYCABLE_RPC_HOST=0.0.0.0:50051
    depends_on:
      - redis
      - db
  anycable:
    image: 'anycable/anycable-go:v0.6.1'
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
      - ANYCABLE_RPC_HOST=rpc:50051
    depends_on:
      - redis
      - rpc
  db:
    image: 'postgres:11.1-alpine'
    volumes:
      - ./docker-volumes/db-data:/var/lib/postgresql/data
  redis:
    image: 'redis:3.2-alpine'
    volumes:
      - ./docker-volumes/redis-data:/data